### What is SVM?

Support Vector Machine (SVM) is a powerful and flexible **supervised machine learning algorithm** used for both **classification** and **regression** tasks, though it's most commonly associated with classification. The core idea behind SVM is to find an **optimal hyperplane** that best separates different classes in a dataset.

Here's a breakdown of key concepts:

* **Hyperplane:** In a 2D space, this is a line. In a 3D space, it's a plane. In higher dimensions, it's a "hyperplane" – a decision boundary that separates data points belonging to different classes.
* **Margin:** SVM aims to find the hyperplane that has the largest possible distance (the "margin") to the nearest data points of each class. A larger margin generally indicates better generalization performance on unseen data.
* **Support Vectors:** These are the data points from each class that are closest to the hyperplane. They are crucial because they directly influence the position and orientation of the optimal hyperplane and the width of the margin. Only these support vectors are needed to define the decision boundary; other data points don't affect it.
* **Kernel Trick:** When data is not linearly separable in its original dimension (i.e., you can't draw a straight line or flat plane to separate the classes), SVM uses a "kernel function" to implicitly map the data into a higher-dimensional space where it *can* be linearly separated. This avoids computationally expensive explicit transformations.

### Types of SVM

SVMs can be broadly categorized based on how they handle data separability:

1.  **Linear SVM:**
    * Used when the data points from different classes can be perfectly separated by a straight line (in 2D), a plane (in 3D), or a hyperplane (in higher dimensions).
    * It aims to find the single best linear decision boundary that maximizes the margin.

2.  **Non-Linear SVM:**
    * Used when the data is not linearly separable in its original feature space.
    * This is where the "kernel trick" comes into play. Kernel functions (like Radial Basis Function (RBF), Polynomial, or Sigmoid) transform the data into a higher-dimensional space, making it linearly separable there. The SVM then finds a linear hyperplane in this transformed space, which corresponds to a non-linear decision boundary in the original space.
    * **Hard Margin SVM:** A strict version that requires perfect separation of classes with no misclassifications within the training data. It's sensitive to outliers and works best when data is perfectly separable.
    * **Soft Margin SVM:** A more flexible version that allows for some misclassifications or violations of the margin to achieve better generalization and handle noisy or overlapping data. It introduces "slack variables" and a regularization parameter (C) to control the trade-off between maximizing the margin and minimizing classification errors.

Beyond these primary types, there are also specialized SVM variants for specific tasks:

* **One-Class SVM:** Used for anomaly or novelty detection, where the goal is to learn the boundary of a single class of "normal" observations and identify any new observations that fall outside this boundary as anomalies.
* **Support Vector Regression (SVR):** An adaptation of SVM for regression problems, where the goal is to predict a continuous output variable instead of a categorical class. It finds a function that fits the data points while minimizing the prediction error, often by finding a hyperplane that best approximates the data within a certain tolerance.
* **Nu-SVM:** A variant that uses a parameter 'nu' to control the number of support vectors and the margin width, offering another way to balance model complexity and generalization.
* **Weighted SVM:** Assigns different weights to different classes, useful for handling imbalanced datasets where some classes have significantly fewer samples than others.

### Applications of SVM in Machine Learning

SVMs are widely applied across various domains due to their effectiveness, especially in high-dimensional spaces and with complex datasets. Some common applications include:

1.  **Image Classification and Recognition:**
    * **Face Detection:** Classifying parts of an image as a face or non-face.
    * **Handwriting Recognition:** Recognizing handwritten characters and digits.
    * **Object Recognition:** Identifying objects within images.
    * **Medical Image Analysis:** Detecting tumors, classifying skin lesions, or diagnosing diseases from medical scans.

2.  **Text Classification and Natural Language Processing (NLP):**
    * **Spam Detection:** Classifying emails as spam or not spam.
    * **Sentiment Analysis:** Determining the emotional tone (positive, negative, neutral) of text data like reviews or social media posts.
    * **News Article Categorization:** Classifying articles into different topics (e.g., business, sports, politics).
    * **Document Classification:** Automatically organizing documents into predefined categories.

3.  **Bioinformatics and Computational Biology:**
    * **Protein Classification:** Categorizing proteins based on their sequences or structures.
    * **Gene Expression Analysis:** Classifying genes or patients based on gene expression patterns.
    * **Disease Diagnosis:** Predicting diseases based on biological markers.

4.  **Credit Scoring and Fraud Detection:**
    * Identifying fraudulent transactions (e.g., credit card fraud) by detecting unusual patterns.
    * Assessing creditworthiness of loan applicants.

5.  **Biomedical Signal Processing:**
    * Analyzing medical signals like ECG or EEG for diagnostic purposes.

6.  **Time Series Prediction:** While more commonly used for classification, SVR can be applied to predict continuous values in time series data.

7.  **Other Niche Applications:**
    * **Geosounding Problem:** Analyzing electromagnetic data to determine the Earth's layered structure.
    * **Surface Texture Classification:** Classifying surfaces based on their texture features.
    * **Intrusion Detection Systems:** Identifying malicious activities in network traffic.

SVM's ability to handle high-dimensional data, its robustness against overfitting (especially with soft margins), and the flexibility offered by kernel functions make it a valuable tool in many machine learning scenarios.

![SVM visualization](SVM.jpg)

In [1]:
# importing library
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns


In [4]:
# importing mL library
from sklearn.svm import SVC
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
from sklearn.preprocessing import LabelEncoder

In [5]:
# import dataset
df=sns.load_dataset('iris')

In [6]:
df.head()

sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [7]:
# find X and y
X = df.drop('species', axis=1)  
y = df['species']

In [8]:
# splitting the dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
# creating the SVM model
model = SVC()
# training the model
model.fit(X_train, y_train)
# making predictions
y_pred = model.predict(X_test)


In [11]:
# evaluating the model
accuracy = accuracy_score(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)
cless_report = classification_report(y_test, y_pred)

In [12]:
print("Accuracy:", accuracy)
print("----------------------------------------")
print("Confusion Matrix:\n", conf_matrix)
print("----------------------------------------")
print("Classification Matric:\n", cless_report)
 


Accuracy: 1.0
----------------------------------------
Confusion Matrix:
 [[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]
----------------------------------------
Classification Matric:
               precision    recall  f1-score   support

      setosa       1.00      1.00      1.00        10
  versicolor       1.00      1.00      1.00         9
   virginica       1.00      1.00      1.00        11

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30



In [15]:

def predict_species(sepal_length, sepal_width, petal_length, petal_width):
    input_data = np.array([[sepal_length, sepal_width, petal_length, petal_width]])
    prediction = model.predict(input_data)
    return prediction[0]


In [16]:
# write a code that user can input a  value using imput function  and predict the species of iris
sepal_length = float(input("Enter sepal length: "))
sepal_width = float(input("Enter sepal width: "))
petal_length = float(input("Enter petal length: "))
petal_width = float(input("Enter petal width: "))
predicted_species = predict_species(sepal_length, sepal_width, petal_length, petal_width)
print(f"The predicted species is: {predicted_species}")

The predicted species is: virginica


c:\Users\SIZAN\miniconda3\envs\data_science_env\lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but SVC was fitted with feature names
  warnings.warn(
